Add regression test
EducationalTestingService/gector pull request #11
Opened 2022-10-06 17:41 UTC by Frost45

Add script for running regression tests.

Once this PR is merged, we are ready to submit our first PR to the upstream repo (Grammarly's GECToR repo).

To test, run `python regression_tests/test_gector_roberta.py` from the base `gector` directory.

2022-10-06 17:55 UTC, desilinguist requested changes
Looks great! Just a few minor comments.

2022-10-06 17:55 UTC, desilinguist commented on regression_tests/test_gector_roberta.py
> +    model_url = "https://grammarly-nlp-data-public.s3.amazonaws.com/gector/roberta_1_gectorv2.th"
This can be a constant, right?

2022-10-06 17:55 UTC, desilinguist commented on regression_tests/test_gector_roberta.py
> +    result_lines = [" ".join(x) for x in predictions]
```suggestion
    result_lines = [" ".join(pred) for pred in predictions]
```

2022-10-06 17:55 UTC, desilinguist commented on regression_tests/test_gector_roberta.py
> +    Generate predictions for all test files and tests that there are no changes.
```suggestion
    Generate predictions for all test files and test that there are no changes.
```

2022-10-06 17:55 UTC, desilinguist commented on regression_tests/test_gector_roberta.py
> +            input_file = str(ORIG_FILE_DIR.joinpath(child.name))
```suggestion
            input_file = str(child.resolve())
```

2022-10-10 18:15 UTC, desilinguist approved these changes
LGTM!

2022-10-10 18:59 UTC, damien2012eng commented on regression_tests/test_gector_roberta.py
> +    return cnt_corrections
The `cnt_corrections` is not used anywhere. Should we just delete this line?

2022-10-10 19:01 UTC, damien2012eng commented
Looks great to me! Just have a nitpick.

2022-10-11 18:51 UTC, damien2012eng commented
One more favor to ask: in the `test_tokenization.py`, the class name is incorrect. The class name should start with `Test` (detailed discussion [here](https://stackoverflow.com/questions/37353960/pytest-exits-with-no-error-but-with-collected-0-items)), otherwise pytest will not able to gather tests. So could you please change the class name from `TokenizationTests` to `TestTokenization`?

2022-10-12 16:27 UTC, damien2012eng approved these changes

2022-10-12 16:28 UTC, merged